name: CI & CD
on: push
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v2

      - name: JDK 17 설치
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: 빌드
        run: | 
          chmod +x gradlew
          ./gradlew build